spring:
  application:
    name: mil
  datasource:
    url: jdbc:postgresql://localhost:5432/mil
    username: postgres
    password: 2635
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8081
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret=key}
